version: '3.8'

services:
  alphagenome-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - ALPHA_GENOME_API_KEY=${ALPHA_GENOME_API_KEY}
      - HOST=0.0.0.0
      - PORT=8000
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

  # Optional: Nginx reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - alphagenome-api
    restart: unless-stopped
    profiles:
      - production

volumes:
  app_data: 